name: royal_hotels
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # ******** PACKAGE YAHAN DAALO (dev_dependencies ke ANDAR) ********
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # ******** ASSETS KO ENABLE KARO ********
  assets:
    # - assets/images/logo.png # Navbar ke liye logo
    - assets/images/app_icon.png # App icon (launcher icon)

# ******** CONFIG (SETTINGS) ROOT LEVEL PAR ********
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
